const EXTRA_PRODUCTS = [
  { id: 16, name: 'Rust Suede Jacket', category: 'Outerwear', price: 2999, image: 'assets/product-016.jpg', badge: 'New' },
  { id: 17, name: 'Stone Co-Ord Set', category: 'Tops', price: 2799, image: 'assets/product-017.jpg', badge: '' },
  { id: 18, name: 'Hazel Knit Cardigan', category: 'Knitwear', price: 2499, image: 'assets/product-018.jpg', badge: '' },
  { id: 19, name: 'Burgundy Velvet Blazer', category: 'Outerwear', price: 2999, image: 'assets/product-019.jpg', badge: 'Premium' },
  { id: 20, name: 'Oat Linen Shirt', category: 'Shirts', price: 1899, image: 'assets/product-020.jpg', badge: 'New' },
  { id: 21, name: 'Noir Wool Overcoat', category: 'Outerwear', price: 2999, image: 'assets/product-021.jpg', badge: '' },
  { id: 22, name: 'Blush Knit Polo', category: 'Knitwear', price: 1699, image: 'assets/product-022.jpg', badge: 'Bestseller' },
  { id: 23, name: 'Forest Cargo Pants', category: 'Bottoms', price: 2199, image: 'assets/product-023.jpg', badge: '' },
  { id: 24, name: 'Midnight Silk Shirt', category: 'Shirts', price: 1599, image: 'assets/product-024.jpg', badge: '' },
  { id: 25, name: 'Taupe Chino Trousers', category: 'Bottoms', price: 1999, image: 'assets/product-025.jpg', badge: 'New' },
  { id: 26, name: 'Ivory Cable Knit', category: 'Knitwear', price: 2699, image: 'assets/product-026.jpg', badge: '' },
  { id: 27, name: 'Copper Satin Shirt', category: 'Shirts', price: 2399, image: 'assets/product-027.jpg', badge: '' },
  { id: 28, name: 'Cream Linen Shirt', category: 'Shirts', price: 1799, image: 'assets/product-028.jpg', badge: '' },
  { id: 29, name: 'Champagne Double-Breasted Coat', category: 'Outerwear', price: 2899, image: 'assets/product-029.jpg', badge: 'New' },
  { id: 30, name: 'Sand Linen Shorts', category: 'Bottoms', price: 1499, image: 'assets/product-030.jpg', badge: '' },
  { id: 31, name: 'Chestnut Knit Polo', category: 'Knitwear', price: 1999, image: 'assets/product-031.jpg', badge: '' },
  { id: 32, name: 'Graphite Puffer Vest', category: 'Outerwear', price: 2999, image: 'assets/product-032.jpg', badge: 'Premium' },
  { id: 33, name: 'Mocha Wide Trousers', category: 'Bottoms', price: 2099, image: 'assets/product-033.jpg', badge: '' },
  { id: 34, name: 'Rose Gold Dress Shirt', category: 'Shirts', price: 1899, image: 'assets/product-034.jpg', badge: 'Bestseller' },
  { id: 35, name: 'Olive Utility Jacket', category: 'Outerwear', price: 2799, image: 'assets/product-035.jpg', badge: '' },
];
